# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SW3yYNMtlPKLfnhSmTjzOAP7al5Y_h7U
"""

!pip install dash plotly pandas dash-bootstrap-components

import dash
from dash import dcc, html, dash_table, Input, Output
import plotly.express as px
import pandas as pd
import numpy as np

# 1. Dataset Histórico con Meses y Años (2019 - 2026)
np.random.seed(42)
years = list(range(2019, 2027))
months_order = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
proveedores = ["EveryMatrix", "Betfounders", "Elantil", "Calimaco", "IGP", "SoftGamings", "RubyPlay", "SkillOnNet", "Yggdrasil", "Pragmatic Play"]
plataformas = ["Casino LatAm", "BetGlobal", "PlayEuro", "Vegas Online", "WinMaster"]

data = []
for y in years:
    growth = 1.0 + (y - 2019) * 0.22  # Tendencia de crecimiento continuo
    for m in months_order:
        for _ in range(np.random.randint(4, 8)):
            prov = np.random.choice(proveedores)
            plat = np.random.choice(plataformas)
            units = int(np.random.randint(1200, 4800) * growth)
            estado = np.random.choice(["Abastecido", "En Tránsito", "Crítico"], p=[0.70, 0.20, 0.10])
            data.append({
                "Proveedor": prov,
                "Juego": f"{prov[:4]}_Slot_{np.random.randint(100, 999)}",
                "Plataforma_Destino": plat,
                "Unidades_Enviadas": units,
                "Estado_Stock": estado,
                "Mes": m,
                "Year": y
            })

df = pd.DataFrame(data)

# 2. Inicializar App
app = dash.Dash(__name__)

THEME_DARK = {'backgroundColor': '#0b1f3a', 'color': 'white', 'fontFamily': 'Arial, sans-serif'}
CARD_STYLE = {
    'backgroundColor': '#0f3460',
    'color': 'white',
    'padding': '15px',
    'borderRadius': '8px',
    'boxShadow': '0 4px 8px rgba(0,0,0,0.3)',
    'marginBottom': '15px'
}

# 3. Layout del Dashboard
app.layout = html.Div(style={**THEME_DARK, 'padding': '20px'}, children=[

    # Header y Filtros
    html.Div(style={'display': 'flex', 'justifyContent': 'space-between', 'alignItems': 'center', 'backgroundColor': '#16213e', 'padding': '15px 25px', 'borderRadius': '8px', 'marginBottom': '20px'}, children=[
        html.Div([
            html.H2("DISTRIBUCIÓN Y ABASTECIMIENTO DE JUEGOS (2019 - 2026)", style={'margin': 0, 'color': '#00fff5', 'fontSize': '22px'}),
            html.P("Análisis histórico y evolutivo mensual / anual de distribución", style={'margin': 0, 'color': '#a2a8d3', 'fontSize': '12px'})
        ]),

        # Filtros: Proveedor, Año y Mes
        html.Div(style={'display': 'flex', 'gap': '12px'}, children=[
            html.Div([
                html.Label("Proveedor", style={'color': '#a2a8d3', 'fontSize': '11px', 'fontWeight': 'bold'}),
                dcc.Dropdown(
                    id='filter-prov',
                    options=[{'label': 'Todos', 'value': 'Todos'}] + [{'label': p, 'value': p} for p in sorted(df['Proveedor'].unique())],
                    value='Todos',
                    clearable=False,
                    style={'width': '150px', 'color': '#000'}
                )
            ]),
            html.Div([
                html.Label("Año", style={'color': '#a2a8d3', 'fontSize': '11px', 'fontWeight': 'bold'}),
                dcc.Dropdown(
                    id='filter-year',
                    options=[{'label': 'Todos los Años', 'value': 'Todos'}] + [{'label': str(y), 'value': y} for y in years],
                    value='Todos',
                    clearable=False,
                    style={'width': '140px', 'color': '#000'}
                )
            ]),
            html.Div([
                html.Label("Mes", style={'color': '#a2a8d3', 'fontSize': '11px', 'fontWeight': 'bold'}),
                dcc.Dropdown(
                    id='filter-month',
                    options=[{'label': 'Todos los Meses', 'value': 'Todos'}] + [{'label': m, 'value': m} for m in months_order],
                    value='Todos',
                    clearable=False,
                    style={'width': '140px', 'color': '#000'}
                )
            ]),
        ])
    ]),

    # Gráfico Superior: Evolución Mensual / Anual
    html.Div(style=CARD_STYLE, children=[
        html.H4("Evolución Temporal del Abastecimiento", style={'fontSize': '15px', 'margin': '0 0 10px 0', 'color': '#00fff5'}),
        dcc.Graph(id="trend-chart", config={'displayModeBar': False})
    ]),

    # Fila Inferior: KPI + Barras + Red + Tabla
    html.Div(style={'display': 'grid', 'gridTemplateColumns': '1.1fr 1.5fr 1.2fr', 'gap': '15px'}, children=[

        # Columna 1: KPI + Barras por Proveedor
        html.Div([
            html.Div(style=CARD_STYLE, children=[
                html.H4("Total Unidades Distribuidas", style={'margin': '0', 'fontSize': '13px', 'color': '#a2a8d3', 'textAlign': 'center'}),
                html.H1(id="kpi-units", style={'margin': '10px 0 0 0', 'color': '#00fff5', 'textAlign': 'center', 'fontSize': '38px'})
            ]),
            html.Div(style=CARD_STYLE, children=[
                html.H4("Volumen por Proveedor", style={'fontSize': '14px', 'marginBottom': '10px'}),
                dcc.Graph(id="bar-chart", config={'displayModeBar': False})
            ])
        ]),

        # Columna 2: Red / Matriz de Plataformas
        html.Div(style=CARD_STYLE, children=[
            html.H4("Distribución por Plataformas de Destino", style={'fontSize': '14px', 'marginBottom': '10px', 'textAlign': 'center'}),
            dcc.Graph(id="network-chart", config={'displayModeBar': False})
        ]),

        # Columna 3: Tabla Detallada
        html.Div(style=CARD_STYLE, children=[
            html.H4("Detalle de Registros", style={'fontSize': '14px', 'marginBottom': '10px'}),
            dash_table.DataTable(
                id='data-table',
                columns=[
                    {"name": "Año", "id": "Year"},
                    {"name": "Mes", "id": "Mes"},
                    {"name": "Proveedor", "id": "Proveedor"},
                    {"name": "Unidades", "id": "Unidades_Enviadas"},
                    {"name": "Estado", "id": "Estado_Stock"}
                ],
                style_header={'backgroundColor': '#16213e', 'color': '#00fff5', 'fontWeight': 'bold', 'border': 'none'},
                style_cell={'backgroundColor': '#0f3460', 'color': 'white', 'textAlign': 'left', 'fontSize': '11px', 'border': '1px solid #16213e'},
                style_data_conditional=[
                    {'if': {'column_id': 'Estado_Stock', 'filter_query': '{Estado_Stock} eq "Crítico"'}, 'color': '#ff4d4d', 'fontWeight': 'bold'},
                    {'if': {'column_id': 'Estado_Stock', 'filter_query': '{Estado_Stock} eq "En Tránsito"'}, 'color': '#ffcc00'},
                    {'if': {'column_id': 'Estado_Stock', 'filter_query': '{Estado_Stock} eq "Abastecido"'}, 'color': '#00ff88'}
                ],
                page_size=7
            )
        ])
    ])
])

# 4. Callback Dinámico
@app.callback(
    [Output('trend-chart', 'figure'),
     Output('kpi-units', 'children'),
     Output('bar-chart', 'figure'),
     Output('network-chart', 'figure'),
     Output('data-table', 'data')],
    [Input('filter-prov', 'value'),
     Input('filter-year', 'value'),
     Input('filter-month', 'value')]
)
def update_metrics(selected_prov, selected_year, selected_month):
    dff = df.copy()

    # Aplicar Filtro de Proveedor
    if selected_prov != 'Todos':
        dff = dff[dff['Proveedor'] == selected_prov]

    # 1. Generar Gráfico de Tendencia según los Filtros seleccionados
    if selected_year == 'Todos':
        # Mostrar tendencia año tras año
        trend_df = dff.groupby('Year')['Unidades_Enviadas'].sum().reset_index()
        fig_trend = px.area(trend_df, x='Year', y='Unidades_Enviadas', markers=True, text='Unidades_Enviadas')
        fig_trend.update_xaxes(dtick=1)
    else:
        # Mostrar tendencia mes a mes dentro del año seleccionado
        dff_trend_year = dff[dff['Year'] == selected_year]
        trend_df = dff_trend_year.groupby('Mes')['Unidades_Enviadas'].sum().reindex(months_order).reset_index()
        fig_trend = px.line(trend_df, x='Mes', y='Unidades_Enviadas', markers=True, text='Unidades_Enviadas')

    fig_trend.update_traces(
        line_color='#00fff5',
        fillcolor='rgba(0, 255, 245, 0.15)' if selected_year == 'Todos' else None,
        textposition='top center',
        texttemplate='%{text:,.0f}'
    )
    fig_trend.update_layout(
        paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
        font=dict(color='white', size=11),
        xaxis=dict(showgrid=True, gridcolor='#16213e'),
        yaxis=dict(showgrid=True, gridcolor='#16213e', title="Unidades Totales"),
        margin=dict(l=20, r=20, t=10, b=20),
        height=220
    )

    # Aplicar Filtros Secundarios de Año y Mes al resto de componentes
    dff_filtered = dff.copy()
    if selected_year != 'Todos':
        dff_filtered = dff_filtered[dff_filtered['Year'] == selected_year]
    if selected_month != 'Todos':
        dff_filtered = dff_filtered[dff_filtered['Mes'] == selected_month]

    # 2. KPI Total
    total_unidades = f"{dff_filtered['Unidades_Enviadas'].sum():,}"

    # 3. Bar Chart por Proveedor
    prov_summary = dff_filtered.groupby('Proveedor')['Unidades_Enviadas'].sum().reset_index().sort_values(by='Unidades_Enviadas', ascending=True)
    fig_bar = px.bar(prov_summary, x='Unidades_Enviadas', y='Proveedor', orientation='h', text='Unidades_Enviadas')
    fig_bar.update_traces(marker_color='#00fff5', textposition='outside', texttemplate='%{text:,.0f}')
    fig_bar.update_layout(
        paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
        font=dict(color='white', size=10),
        xaxis=dict(showgrid=False, visible=False),
        yaxis=dict(showgrid=False),
        margin=dict(l=0, r=50, t=10, b=10),
        height=300
    )

    # 4. Network/Scatter Chart por Plataforma
    fig_network = px.scatter(
        dff_filtered, x='Plataforma_Destino', y='Proveedor', size='Unidades_Enviadas',
        color='Estado_Stock', hover_name='Juego', size_max=28,
        color_discrete_map={'Abastecido': '#00ff88', 'En Tránsito': '#ffcc00', 'Crítico': '#ff4d4d'}
    )
    fig_network.update_layout(
        paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
        font=dict(color='white', size=10),
        xaxis=dict(showgrid=True, gridcolor='#16213e', title="Plataforma de Destino"),
        yaxis=dict(showgrid=True, gridcolor='#16213e', title=""),
        margin=dict(l=10, r=10, t=10, b=20),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=360
    )

    return fig_trend, total_unidades, fig_bar, fig_network, dff_filtered.tail(15).to_dict('records')

# 5. Servidor para Google Colab
app.run(jupyter_mode='inline', jupyter_height=900)